name: Deploy to Vercel Development

on:
    push:
        branches:
            - staging

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install Yarn
              run: npm install -g yarn

            - name: Install dependencies
              run: yarn install

            - name: Check lint and format
              run: yarn test-all

            - name: Deploy to Vercel
              uses: amondnet/vercel-action@v20
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} # Replace with your Vercel team ID
                  vercel-project-id: ${{ secrets.VERCEL_DEV_PROJECT_ID }}
                  vercel-args: '--prod'